// Dados mockados para demonstração
export const destinations = [
  {
    $id: "1",
    name: "Rio de Janeiro",
    description:
      "Cidade maravilhosa com praias deslumbrantes, pontos turísticos icônicos e rica vida cultural.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1299.9,
    country: "Brasil",
    city: "Rio de Janeiro",
    region: "Sudeste",
    rating: 4.8,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Cultura",
        description: "Destinos com rica herança cultural",
        icon: "culture",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre maio e setembro",
  },
  {
    $id: "2",
    name: "Fernando de Noronha",
    description:
      "Arquipélago paradisíaco com as mais belas praias do Brasil, vida marinha abundante e natureza preservada.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 3599.9,
    country: "Brasil",
    city: "Fernando de Noronha",
    region: "Nordeste",
    rating: 4.9,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Natureza",
        description: "Destinos com belezas naturais",
        icon: "nature",
      },
    ],
    discount: 0,
    timezone: "America/Noronha",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre agosto e janeiro",
  },
  {
    $id: "3",
    name: "Gramado",
    description:
      "Cidade com arquitetura européia, gastronomia refinada e atrações turísticas para toda família.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1899.9,
    country: "Brasil",
    city: "Gramado",
    region: "Sul",
    rating: 4.7,
    categories: [
      {
        name: "Montanha",
        description: "Destinos montanhosos",
        icon: "mountain",
      },
      {
        name: "Romântico",
        description: "Destinos ideais para casais",
        icon: "heart",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Subtropical",
    currency: "BRL",
    bestTimeToVisit: "Entre junho e agosto",
  },
  {
    $id: "4",
    name: "Bonito",
    description:
      "Destino ecoturístico com rios cristalinos, grutas e cachoeiras impressionantes.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1599.9,
    country: "Brasil",
    city: "Bonito",
    region: "Centro-Oeste",
    rating: 4.6,
    categories: [
      {
        name: "Natureza",
        description: "Destinos com belezas naturais",
        icon: "nature",
      },
      {
        name: "Aventura",
        description: "Destinos para aventureiros",
        icon: "adventure",
      },
    ],
    discount: 0,
    timezone: "America/Campo_Grande",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre abril e novembro",
  },
  {
    $id: "5",
    name: "Florianópolis",
    description:
      "Capital com mais de 40 praias, gastronomia local rica e qualidade de vida excepcional.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1499.9,
    country: "Brasil",
    city: "Florianópolis",
    region: "Sul",
    rating: 4.7,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Gastronomia",
        description: "Destinos com excelente culinária",
        icon: "food",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Subtropical",
    currency: "BRL",
    bestTimeToVisit: "Entre dezembro e março",
  },
  {
    $id: "6",
    name: "Salvador",
    description:
      "Primeira capital do Brasil, rica em história, cultura afro-brasileira e praias urbanas.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1399.9,
    country: "Brasil",
    city: "Salvador",
    region: "Nordeste",
    rating: 4.6,
    categories: [
      {
        name: "Cultura",
        description: "Destinos com rica herança cultural",
        icon: "culture",
      },
      {
        name: "História",
        description: "Destinos históricos importantes",
        icon: "history",
      },
    ],
    discount: 0,
    timezone: "America/Bahia",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre setembro e março",
  },
  {
    $id: "7",
    name: "Manaus",
    description:
      "Portal da Amazônia, com encontro das águas, teatro histórico e experiências na floresta.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1799.9,
    country: "Brasil",
    city: "Manaus",
    region: "Norte",
    rating: 4.5,
    categories: [
      {
        name: "Natureza",
        description: "Destinos com belezas naturais",
        icon: "nature",
      },
      {
        name: "Aventura",
        description: "Destinos para aventureiros",
        icon: "adventure",
      },
    ],
    discount: 0,
    timezone: "America/Manaus",
    languages: ["Português"],
    climate: "Equatorial",
    currency: "BRL",
    bestTimeToVisit: "Entre junho e setembro",
  },
  {
    $id: "8",
    name: "Maceió",
    description:
      "Capital com praias de águas cristalinas, piscinas naturais e gastronomia típica.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1299.9,
    country: "Brasil",
    city: "Maceió",
    region: "Nordeste",
    rating: 4.7,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Gastronomia",
        description: "Destinos com excelente culinária",
        icon: "food",
      },
    ],
    discount: 0,
    timezone: "America/Maceio",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre setembro e março",
  },
  {
    $id: "9",
    name: "Curitiba",
    description:
      "Cidade modelo em planejamento urbano, com parques verdes e atrações culturais.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1699.9,
    country: "Brasil",
    city: "Curitiba",
    region: "Sul",
    rating: 4.6,
    categories: [
      {
        name: "Cidade",
        description: "Destinos urbanos",
        icon: "city",
      },
      {
        name: "Cultura",
        description: "Destinos com rica herança cultural",
        icon: "culture",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Subtropical",
    currency: "BRL",
    bestTimeToVisit: "Entre março e maio",
  },
  {
    $id: "10",
    name: "Porto de Galinhas",
    description:
      "Destino com piscinas naturais, praias paradisíacas e estrutura turística completa.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1899.9,
    country: "Brasil",
    city: "Ipojuca",
    region: "Nordeste",
    rating: 4.8,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Família",
        description: "Destinos ideais para família",
        icon: "family",
      },
    ],
    discount: 0,
    timezone: "America/Recife",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre setembro e março",
  },
  {
    $id: "11",
    name: "Ouro Preto",
    description:
      "Cidade histórica com rica arquitetura barroca e importante patrimônio cultural.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1299.9,
    country: "Brasil",
    city: "Ouro Preto",
    region: "Sudeste",
    rating: 4.7,
    categories: [
      {
        name: "História",
        description: "Destinos históricos importantes",
        icon: "history",
      },
      {
        name: "Cultura",
        description: "Destinos com rica herança cultural",
        icon: "culture",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Tropical de Altitude",
    currency: "BRL",
    bestTimeToVisit: "Entre abril e setembro",
  },
  {
    $id: "12",
    name: "Campos do Jordão",
    description:
      "Cidade de montanha com arquitetura européia, gastronomia refinada e clima ameno.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1599.9,
    country: "Brasil",
    city: "Campos do Jordão",
    region: "Sudeste",
    rating: 4.6,
    categories: [
      {
        name: "Montanha",
        description: "Destinos montanhosos",
        icon: "mountain",
      },
      {
        name: "Romântico",
        description: "Destinos ideais para casais",
        icon: "heart",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Subtropical de Altitude",
    currency: "BRL",
    bestTimeToVisit: "Entre junho e agosto",
  },
  {
    $id: "13",
    name: "Jericoacoara",
    description:
      "Vila de pescadores transformada em paraíso turístico, com dunas e praias selvagens.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 2199.9,
    country: "Brasil",
    city: "Jijoca de Jericoacoara",
    region: "Nordeste",
    rating: 4.8,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Aventura",
        description: "Destinos para aventureiros",
        icon: "adventure",
      },
    ],
    discount: 0,
    timezone: "America/Fortaleza",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre julho e dezembro",
  },
  {
    $id: "14",
    name: "Chapada dos Veadeiros",
    description:
      "Parque Nacional com cachoeiras cristalinas, trilhas e paisagens deslumbrantes.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1499.9,
    country: "Brasil",
    city: "Alto Paraíso de Goiás",
    region: "Centro-Oeste",
    rating: 4.7,
    categories: [
      {
        name: "Natureza",
        description: "Destinos com belezas naturais",
        icon: "nature",
      },
      {
        name: "Aventura",
        description: "Destinos para aventureiros",
        icon: "adventure",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Tropical de Altitude",
    currency: "BRL",
    bestTimeToVisit: "Entre maio e setembro",
  },
  {
    $id: "15",
    name: "Paraty",
    description:
      "Cidade histórica com centro preservado, praias paradisíacas e cultura rica.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1399.9,
    country: "Brasil",
    city: "Paraty",
    region: "Sudeste",
    rating: 4.6,
    categories: [
      {
        name: "História",
        description: "Destinos históricos importantes",
        icon: "history",
      },
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
    ],
    discount: 0,
    timezone: "America/Sao_Paulo",
    languages: ["Português"],
    climate: "Tropical",
    currency: "BRL",
    bestTimeToVisit: "Entre abril e outubro",
  },
];
export const popularDestinations = [
  {
    $id: "1",
    name: "Rio de Janeiro",
    description:
      "Cidade maravilhosa com praias deslumbrantes e pontos turísticos icônicos.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1299.9,
    country: "Brasil",
    city: "Rio de Janeiro",
    region: "Sudeste",
    rating: 4.8,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Cultura",
        description: "Destinos com rica herança cultural",
        icon: "culture",
      },
    ],
    discount: 0,
  },
  {
    $id: "2",
    name: "Fernando de Noronha",
    description: "Arquipélago paradisíaco com as mais belas praias do Brasil.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 3599.9,
    country: "Brasil",
    city: "Fernando de Noronha",
    region: "Nordeste",
    rating: 4.9,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Natureza",
        description: "Destinos com belezas naturais",
        icon: "nature",
      },
    ],
    discount: 0,
  },
  {
    $id: "3",
    name: "Gramado",
    description:
      "Cidade com arquitetura européia e clima romântico na Serra Gaúcha.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1899.9,
    country: "Brasil",
    city: "Gramado",
    region: "Sul",
    rating: 4.7,
    categories: [
      {
        name: "Montanha",
        description: "Destinos montanhosos",
        icon: "mountain",
      },
      {
        name: "Romântico",
        description: "Destinos ideais para casais",
        icon: "heart",
      },
    ],
    discount: 0,
  },
  {
    $id: "4",
    name: "Bonito",
    description:
      "Paraíso do ecoturismo com águas cristalinas e grutas impressionantes.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 1599.9,
    country: "Brasil",
    city: "Bonito",
    region: "Centro-Oeste",
    rating: 4.6,
    categories: [
      {
        name: "Natureza",
        description: "Destinos com belezas naturais",
        icon: "nature",
      },
      {
        name: "Aventura",
        description: "Destinos para aventureiros",
        icon: "adventure",
      },
    ],
    discount: 0,
  },
];

export const promotions = [
  {
    $id: "1",
    name: "Cancún",
    description:
      "Praias paradisíacas e resorts all-inclusive no Caribe mexicano.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 4999.9,
    country: "México",
    city: "Cancún",
    region: "Quintana Roo",
    rating: 4.7,
    categories: [
      {
        name: "Praia",
        description: "Destinos com belas praias",
        icon: "beach",
      },
      {
        name: "Resort",
        description: "Destinos com resorts all-inclusive",
        icon: "hotel",
      },
    ],
    discount: 25,
  },
  {
    $id: "2",
    name: "Buenos Aires",
    description: "Capital argentina com rica cultura e arquitetura histórica.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 2899.9,
    country: "Argentina",
    city: "Buenos Aires",
    region: "Buenos Aires",
    rating: 4.5,
    categories: [
      {
        name: "Cidade",
        description: "Destinos urbanos",
        icon: "city",
      },
      {
        name: "Cultura",
        description: "Destinos com rica herança cultural",
        icon: "culture",
      },
    ],
    discount: 15,
  },
  {
    $id: "3",
    name: "Orlando",
    description: "Capital mundial dos parques temáticos e diversão em família.",
    mainImage: "/placeholder.svg?height=300&width=500",
    images: [],
    price: 5999.9,
    country: "Estados Unidos",
    city: "Orlando",
    region: "Flórida",
    rating: 4.8,
    categories: [
      {
        name: "Família",
        description: "Destinos ideais para família",
        icon: "family",
      },
      {
        name: "Parques",
        description: "Destinos com parques temáticos",
        icon: "park",
      },
    ],
    discount: 20,
  },
];

export const categories = [
  {
    $id: "1",
    name: "Praias",
    description: "Destinos com as mais belas praias",
    icon: "beach",
    color: "#00B4D8",
  },
  {
    $id: "2",
    name: "Montanhas",
    description: "Destinos com paisagens montanhosas deslumbrantes",
    icon: "mountain",
    color: "#2D3E40",
  },
  {
    $id: "3",
    name: "Cidades",
    description: "Principais destinos urbanos",
    icon: "city",
    color: "#6C757D",
  },
  {
    $id: "4",
    name: "Aventura",
    description: "Destinos para os amantes de aventura",
    icon: "adventure",
    color: "#FF6B6B",
  },
];

export const testimonials = [
  {
    userId: "user1",
    destinationId: "1",
    userName: "João Silva",
    userAvatar: "/placeholder.svg?height=24&width=24",
    rating: 5,
    comment:
      "Viagem incrível para Fernando de Noronha! Tudo foi perfeito, desde o atendimento até a hospedagem. Recomendo muito a BlueDestination!",
    date: new Date().toISOString(),
    helpfulVotes: 12,
    status: "approved",
  },
  {
    userId: "user2",
    destinationId: "2",
    userName: "Maria Silva",
    userAvatar: "/placeholder.svg?height=24&width=24",
    rating: 4,
    comment:
      "Pacote para Gramado com excelente custo-benefício. A agência cuidou de todos os detalhes e não tivemos nenhuma preocupação.",
    date: new Date().toISOString(),
    helpfulVotes: 8,
    status: "approved",
  },
  {
    userId: "user3",
    destinationId: "3",
    userName: "José Silva",
    userAvatar: "/placeholder.svg?height=24&width=24",
    rating: 5,
    comment:
      "Segunda vez que viajo com a BlueDestination e novamente superou minhas expectativas. Atendimento personalizado e ótimas dicas!",
    date: new Date().toISOString(),
    helpfulVotes: 15,
    status: "approved",
  },
];

import type { BlogPost } from "@/schemas/blog";

export const blogPosts: BlogPost[] = [
  {
    $id: "1",
    title: "10 praias paradisíacas no Brasil que você precisa conhecer",
    slug: "10-praias-paradisiacas-no-brasil-que-voce-precisa-conhecer",
    excerpt:
      "Descubra as praias mais bonitas do Brasil, com águas cristalinas e paisagens deslumbrantes que vão te deixar sem fôlego.",
    content: [
      {
        type: "text" as const,
        content: "Conteúdo completo do post...",
        metadata: {},
      },
    ],
    featuredImage: "/placeholder.svg?height=340&width=600",
    status: "published",
    publishedAt: new Date().toISOString(),
    tags: ["Praias", "Brasil", "Viagem"],
    seo: {
      title: "10 praias paradisíacas no Brasil que você precisa conhecer",
      description:
        "Descubra as praias mais bonitas do Brasil, com águas cristalinas e paisagens deslumbrantes que vão te deixar sem fôlego.",
      keywords: ["Praias", "Brasil", "Viagem", "Turismo"],
    },
    readingTime: 5,
    viewsCount: 0,
    relatedContent: {
      destinations: ["dest-1", "dest-2"],
      packages: ["pack-1", "pack-2"],
    },
    settings: {
      allowComments: true,
      featured: false,
      pinned: false,
    },
    author: {
      name: "Juliana Mendes",
      email: "juliana.mendes@example.com",
      bio: "Viajante profissional e escritora de conteúdo de viagem",
      avatar: "/placeholder.svg?height=24&width=24",
      role: "author",
      socialLinks: {
        twitter: "https://twitter.com/julianamendes",
        linkedin: "https://linkedin.com/in/julianamendes",
      },
    },
    categories: [
      {
        name: "Praias",
        slug: "praias",
        description: "Destinos com praias paradisíacas",
        icon: "beach",
        color: "#00B4D8",
      },
    ],
  },
  {
    $id: "2",
    title: "Guia completo: como planejar sua viagem internacional",
    slug: "guia-completo-como-planejar-sua-viagem-internacional",
    excerpt:
      "Tudo o que você precisa saber para organizar sua viagem internacional sem estresse, desde documentação até dicas de economia.",
    content: [
      {
        type: "text" as const,
        content: "Conteúdo completo do post...",
        metadata: {},
      },
    ],
    featuredImage: "/placeholder.svg?height=340&width=600",
    status: "published",
    publishedAt: new Date().toISOString(),
    tags: ["Internacional", "Planejamento", "Dicas"],
    seo: {
      title: "Guia completo: como planejar sua viagem internacional",
      description:
        "Tudo o que você precisa saber para organizar sua viagem internacional sem estresse, desde documentação até dicas de economia.",
      keywords: ["Viagem Internacional", "Planejamento", "Dicas de Viagem"],
    },
    readingTime: 8,
    viewsCount: 0,
    relatedContent: {
      destinations: ["dest-3", "dest-4"],
      packages: ["pack-3", "pack-4"],
    },
    settings: {
      allowComments: true,
      featured: true,
      pinned: false,
    },
    author: {
      name: "Ricardo Almeida",
      email: "ricardo.almeida@example.com",
      bio: "Especialista em viagens internacionais",
      avatar: "/placeholder.svg?height=24&width=24",
      role: "editor",
      socialLinks: {
        twitter: "https://twitter.com/ricardoalmeida",
        linkedin: "https://linkedin.com/in/ricardoalmeida",
      },
    },
    categories: [
      {
        name: "Internacional",
        slug: "internacional",
        description: "Destinos internacionais",
        icon: "globe",
        color: "#2D3E40",
      },
    ],
  },
  {
    $id: "3",
    title: "Viajando com crianças: destinos perfeitos para toda a família",
    slug: "viajando-com-criancas-destinos-perfeitos-para-toda-a-familia",
    excerpt:
      "Conheça os melhores destinos para viajar com crianças, com atrações para todas as idades e dicas para uma viagem tranquila.",
    content: [
      {
        type: "text" as const,
        content: "Conteúdo completo do post...",
        metadata: {},
      },
    ],
    featuredImage: "/placeholder.svg?height=340&width=600",
    status: "published",
    publishedAt: new Date().toISOString(),
    tags: ["Família", "Crianças", "Destinos"],
    seo: {
      title: "Viajando com crianças: destinos perfeitos para toda a família",
      description:
        "Conheça os melhores destinos para viajar com crianças, com atrações para todas as idades e dicas para uma viagem tranquila.",
      keywords: ["Viagem em Família", "Crianças", "Destinos Família"],
    },
    readingTime: 6,
    viewsCount: 0,
    relatedContent: {
      destinations: ["dest-5", "dest-6"],
      packages: ["pack-5", "pack-6"],
    },
    settings: {
      allowComments: true,
      featured: false,
      pinned: true,
    },
    author: {
      name: "Fernanda Santos",
      email: "fernanda.santos@example.com",
      bio: "Especialista em viagens em família",
      avatar: "/placeholder.svg?height=24&width=24",
      role: "author",
      socialLinks: {
        twitter: "https://twitter.com/fernandasantos",
        instagram: "https://instagram.com/fernandasantos",
      },
    },
    categories: [
      {
        name: "Família",
        slug: "familia",
        description: "Viagens em família",
        icon: "family",
        color: "#FF6B6B",
      },
    ],
  },
];

export const user = {
  $id: "user123",
  name: "John Doe",
  email: "john.doe@example.com",
  wishlist: ["destination1", "destination2"],
  reservations: ["reservation1", "reservation2"],
};
