export interface CollectionConfig {
  name: string;
  envKey: string;
  attributes: {
    name: string;
    type: string;
    size?: number;
    required?: boolean;
    default?: any;
    min?: number;
    max?: number;
    array?: boolean;
    relation?: string; // Added relation field for references to other collections
  }[];
}

export const collections: CollectionConfig[] = [
  {
    name: "Users",
    envKey: "NEXT_PUBLIC_COLLECTION_USERS",
    attributes: [
      { name: "name", type: "string", size: 100, required: true },
      { name: "email", type: "string", size: 100, required: true },
      {
        name: "role",
        type: "string",
        size: 20,
        required: true,
        default: "user",
      },
      { name: "avatar", type: "string", size: 255 },
      { name: "phone", type: "string", size: 20 },
      { name: "address", type: "string", size: 100, relation: "Addresses" },
      {
        name: "preferences",
        type: "string",
        size: 100,
        relation: "UserPreferences",
      },
      {
        name: "favorites",
        type: "string",
        size: 100,
        array: true,
        relation: "Favorites",
      },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Addresses",
    envKey: "NEXT_PUBLIC_COLLECTION_ADDRESSES",
    attributes: [
      { name: "street", type: "string", size: 100, required: true },
      { name: "number", type: "string", size: 20, required: true },
      { name: "complement", type: "string", size: 100 },
      { name: "neighborhood", type: "string", size: 100, required: true },
      { name: "city", type: "string", size: 100, required: true },
      { name: "state", type: "string", size: 50, required: true },
      { name: "country", type: "string", size: 50, required: true },
      { name: "zipCode", type: "string", size: 20, required: true },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Destinations",
    envKey: "NEXT_PUBLIC_COLLECTION_DESTINATIONS",
    attributes: [
      { name: "name", type: "string", size: 100, required: true },
      { name: "location", type: "string", size: 100, required: true },
      { name: "description", type: "string", size: 5000, required: true },
      { name: "price", type: "double", required: true, min: 0, max: 1000000 },
      { name: "rating", type: "double", required: true, min: 0, max: 5 },
      { name: "reviewCount", type: "integer", required: true, min: 0 },
      { name: "imageUrl", type: "string", size: 255, required: true },
      { name: "gallery", type: "string", size: 255, array: true },
      { name: "featured", type: "boolean", required: true },
      { name: "popular", type: "boolean" },
      { name: "region", type: "string", size: 50 },
      {
        name: "coordinates",
        type: "json",
        required: false,
        default: {
          latitude: 0,
          longitude: 0,
        },
      },
      {
        name: "weather",
        type: "json",
        required: false,
        default: {
          bestTime: "",
          temperature: {
            min: 0,
            max: 0,
          },
        },
      },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Packages",
    envKey: "NEXT_PUBLIC_COLLECTION_PACKAGES",
    attributes: [
      { name: "name", type: "string", size: 100, required: true },
      { name: "description", type: "string", size: 5000, required: true },
      { name: "imageUrl", type: "string", size: 255, required: true },
      { name: "gallery", type: "string", size: 255, array: true },
      { name: "price", type: "double", required: true, min: 0, max: 1000000 },
      { name: "duration", type: "integer", required: true, min: 1 },
      {
        name: "destinations",
        type: "string",
        size: 100,
        array: true,
        relation: "Destinations",
      },
      { name: "featured", type: "boolean", required: true },
      { name: "discount", type: "string", size: 100, relation: "Discounts" },
      {
        name: "tags",
        type: "string",
        size: 100,
        array: true,
        relation: "Tags",
      },
      {
        name: "inclusions",
        type: "string",
        size: 100,
        array: true,
        relation: "Inclusions",
      },
      { name: "maxGuests", type: "integer", min: 1 },
      { name: "excluded", type: "string", size: 500, array: true },
      {
        name: "itineraries",
        type: "string",
        size: 100,
        array: true,
        relation: "Itinerary",
      },
      {
        name: "testimonials",
        type: "string",
        size: 100,
        array: true,
        relation: "Testimonials",
      },
      {
        name: "bookings",
        type: "string",
        size: 100,
        array: true,
        relation: "Bookings",
      },
      {
        name: "availability",
        type: "string",
        size: 100,
        array: true,
        relation: "Availability",
      },
      { name: "requirements", type: "string", size: 500, array: true },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Activities",
    envKey: "NEXT_PUBLIC_COLLECTION_ACTIVITIES",
    attributes: [
      { name: "name", type: "string", size: 100, required: true },
      { name: "description", type: "string", size: 1000, required: true },
      { name: "location", type: "string", size: 100, required: true },
      { name: "duration", type: "integer", required: true, min: 1 },
      { name: "price", type: "double", required: true, min: 0 },
      { name: "rating", type: "double", required: true, min: 0, max: 5 },
      { name: "reviewCount", type: "integer", required: true, min: 0 },
      { name: "imageUrl", type: "string", size: 255, required: true },
      { name: "featured", type: "boolean", required: true },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Reviews",
    envKey: "NEXT_PUBLIC_COLLECTION_REVIEWS",
    attributes: [
      {
        name: "userId",
        type: "string",
        size: 100,
        required: true,
        relation: "Users",
      },
      { name: "title", type: "string", size: 100, required: true },
      { name: "content", type: "string", size: 2000, required: true },
      { name: "rating", type: "double", required: true, min: 1, max: 5 },
      {
        name: "status",
        type: "string",
        size: 20,
        required: true,
        default: "pending",
      },
      {
        name: "type",
        type: "string",
        size: 20,
        required: true,
      },
      { name: "itemId", type: "string", size: 100, required: true },
      { name: "helpful", type: "integer", default: 0, min: 0 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Testimonials",
    envKey: "NEXT_PUBLIC_COLLECTION_TESTIMONIALS",
    attributes: [
      {
        name: "user",
        type: "string",
        size: 100,
        required: true,
        relation: "Users",
      },
      { name: "package", type: "string", size: 100, relation: "Packages" },
      {
        name: "destination",
        type: "string",
        size: 100,
        relation: "Destinations",
      },
      { name: "rating", type: "double", required: true, min: 1, max: 5 },
      { name: "comment", type: "string", size: 1000, required: true },
      { name: "date", type: "string", size: 50, required: true },
      { name: "featured", type: "boolean", default: false },
      { name: "imageUrl", type: "string", size: 255 },
      { name: "likes", type: "integer", min: 0, default: 0 },
      { name: "helpful", type: "integer", min: 0, default: 0 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Notifications",
    envKey: "NEXT_PUBLIC_COLLECTION_NOTIFICATIONS",
    attributes: [
      { name: "title", type: "string", size: 100, required: true },
      { name: "message", type: "string", size: 500, required: true },
      { name: "type", type: "string", size: 20, required: true },
      { name: "read", type: "boolean", required: true, default: false },
      {
        name: "userId",
        type: "string",
        size: 100,
        required: true,
        relation: "Users",
      },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Bookings",
    envKey: "NEXT_PUBLIC_COLLECTION_BOOKINGS",
    attributes: [
      {
        name: "user",
        type: "string",
        size: 100,
        required: true,
        relation: "Users",
      },
      {
        name: "packages",
        type: "string",
        size: 100,
        required: true,
        relation: "Packages",
      },
      {
        name: "status",
        type: "string",
        size: 20,
        required: true,
        default: "pending",
      },
      { name: "bookingDate", type: "string", size: 50, required: true },
      { name: "travelDate", type: "string", size: 50, required: true },
      { name: "travelers", type: "integer", required: true, min: 1 },
      { name: "totalPrice", type: "double", required: true, min: 0 },
      {
        name: "payment",
        type: "string",
        size: 100,
        required: true,
        relation: "Payments",
      },
      {
        name: "Passengers",
        type: "string",
        size: 100,
        array: true,
        relation: "Passengers",
      },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Itinerary",
    envKey: "NEXT_PUBLIC_COLLECTION_ITINERARY",
    attributes: [
      {
        name: "package",
        type: "string",
        size: 100,
        required: true,
        relation: "Packages",
      },
      { name: "day", type: "integer", required: true, min: 1, max: 365 },
      { name: "title", type: "string", size: 200, required: true },
      { name: "description", type: "string", size: 5000, required: true },
      {
        name: "activities",
        type: "string",
        size: 100,
        array: true,
        relation: "Activities",
      },
      { name: "meals", type: "string", size: 100, relation: "Meals" },
      {
        name: "accommodation",
        type: "string",
        size: 100,
        relation: "Accommodations",
      },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Tags",
    envKey: "NEXT_PUBLIC_COLLECTION_TAGS",
    attributes: [
      { name: "name", type: "string", size: 50, required: true },
      { name: "slug", type: "string", size: 50, required: true },
      {
        name: "type",
        type: "string",
        size: 20,
        required: true,
        default: "destination",
      },
      { name: "description", type: "string", size: 500 },
      { name: "color", type: "string", size: 20 },
      { name: "icon", type: "string", size: 50 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Categories",
    envKey: "NEXT_PUBLIC_COLLECTION_CATEGORIES",
    attributes: [
      { name: "name", type: "string", size: 50, required: true },
      { name: "slug", type: "string", size: 50, required: true },
      { name: "description", type: "string", size: 500 },
      { name: "imageUrl", type: "string", size: 255 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Settings",
    envKey: "NEXT_PUBLIC_COLLECTION_SETTINGS",
    attributes: [
      { name: "key", type: "string", size: 50, required: true },
      { name: "value", type: "string", size: 1000, required: true },
      { name: "group", type: "string", size: 50, required: true },
      { name: "description", type: "string", size: 500 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Meals",
    envKey: "NEXT_PUBLIC_COLLECTION_MEALS",
    attributes: [
      { name: "breakfast", type: "boolean", required: true, default: false },
      { name: "lunch", type: "boolean", required: true, default: false },
      { name: "dinner", type: "boolean", required: true, default: false },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Accommodations",
    envKey: "NEXT_PUBLIC_COLLECTION_ACCOMMODATIONS",
    attributes: [
      { name: "type", type: "string", size: 50, required: true },
      { name: "name", type: "string", size: 100, required: true },
      { name: "rating", type: "double", min: 0, max: 5 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "UserPreferences",
    envKey: "NEXT_PUBLIC_COLLECTION_USER_PREFERENCES",
    attributes: [
      { name: "newsletter", type: "boolean", default: false },
      {
        name: "notifications",
        type: "json",
        required: true,
        default: {
          email: true,
          push: true,
          sms: false,
        },
      },
      {
        name: "currency",
        type: "string",
        size: 3,
        required: true,
        default: "USD",
      },
      {
        name: "language",
        type: "string",
        size: 5,
        required: true,
        default: "en-US",
      },
      { name: "preferredDestinations", type: "string", size: 100, array: true },
      { name: "dietaryRestrictions", type: "string", size: 100, array: true },
      { name: "travelStyle", type: "string", size: 50, array: true },
      { name: "priceRange", type: "string", size: 50 },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
  {
    name: "Discounts",
    envKey: "NEXT_PUBLIC_COLLECTION_DISCOUNTS",
    attributes: [
      {
        name: "type",
        type: "string",
        size: 20,
        required: true,
      },
      {
        name: "value",
        type: "double",
        required: true,
        min: 0,
        max: 100,
      },
      {
        name: "startDate",
        type: "datetime",
        required: true,
      },
      {
        name: "endDate",
        type: "datetime",
        required: true,
      },
      {
        name: "createdAt",
        type: "datetime",
        required: true,
      },
      {
        name: "updatedAt",
        type: "datetime",
        required: true,
      },
    ],
  },
  {
    name: "Inclusions",
    envKey: "NEXT_PUBLIC_COLLECTION_INCLUSIONS",
    attributes: [
      {
        name: "name",
        type: "string",
        size: 100,
        required: true,
      },
      {
        name: "description",
        type: "string",
        size: 500,
        required: true,
      },
      {
        name: "createdAt",
        type: "datetime",
        required: true,
      },
      {
        name: "updatedAt",
        type: "datetime",
        required: true,
      },
    ],
  },
  {
    name: "Availability",
    envKey: "NEXT_PUBLIC_COLLECTION_AVAILABILITY",
    attributes: [
      {
        name: "startDate",
        type: "datetime",
        required: true,
      },
      {
        name: "endDate",
        type: "datetime",
        required: true,
      },
      {
        name: "slots",
        type: "integer",
        required: true,
        min: 0,
      },
      {
        name: "status",
        type: "string",
        size: 20,
        required: true,
        default: "available",
      },
      {
        name: "createdAt",
        type: "datetime",
        required: true,
      },
      {
        name: "updatedAt",
        type: "datetime",
        required: true,
      },
    ],
  },
  {
    name: "Passengers",
    envKey: "NEXT_PUBLIC_COLLECTION_PASSENGERS",
    attributes: [
      {
        name: "name",
        type: "string",
        size: 100,
        required: true,
      },
      {
        name: "document",
        type: "string",
        size: 50,
        required: true,
      },
      {
        name: "birthDate",
        type: "datetime",
        required: true,
      },
      {
        name: "specialNeeds",
        type: "string",
        size: 500,
      },
      {
        name: "createdAt",
        type: "datetime",
        required: true,
      },
      {
        name: "updatedAt",
        type: "datetime",
        required: true,
      },
    ],
  },
  {
    name: "Payments",
    envKey: "NEXT_PUBLIC_COLLECTION_PAYMENTS",
    attributes: [
      {
        name: "booking",
        type: "string",
        size: 100,
        required: true,
        relation: "Bookings",
      },
      { name: "amount", type: "double", required: true, min: 0 },
      { name: "method", type: "string", size: 50, required: true },
      {
        name: "status",
        type: "string",
        size: 20,
        required: true,
        default: "pending",
      },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },

  {
    name: "Favorites",
    envKey: "NEXT_PUBLIC_COLLECTION_FAVORITES",
    attributes: [
      { name: "type", type: "string", size: 20, required: true },
      { name: "itemId", type: "string", size: 100, required: true },
      { name: "createdAt", type: "datetime", required: true },
      { name: "updatedAt", type: "datetime", required: true },
    ],
  },
];
